name: ott
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  carousel_slider: ^5.0.0
  video_player: ^2.8.6
  youtube_player_flutter: ^9.1.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_launcher_icons: ^0.14.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/logo.mp4
    - assets/images/joker.jpg
    - assets/images/master.jpg
    - assets/images/star_wars.jpg
    - assets/images/titanic.jpg
    - assets/images/codeSent.png
    - assets/images/india_flag.png
    - assets/images/pokiri.jpg
    - assets/images/okkadu.jpg
    - assets/images/athadu.jpg
    - assets/images/srimanthudu.jpg
    - assets/images/murari.jpg
    - assets/images/stranger_things.jpg
    - assets/images/Chhota_Bheem.jpg
    - assets/images/planetEarth.jpg
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"