// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnZo6QBcjdPVmqEji_4DRgSiydhpFRa0',
    appId: '1:1095257635223:web:ec4042b347cfec2c69ecd2',
    messagingSenderId: '1095257635223',
    projectId: 'movievault-52674',
    authDomain: 'movievault-52674.firebaseapp.com',
    storageBucket: 'movievault-52674.firebasestorage.app',
    measurementId: 'G-KRPM9QN3FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_2Y7p_fdDjbJP5WYPmCuwFusViBPkKw',
    appId: '1:1095257635223:android:d7c7dd197db3585a69ecd2',
    messagingSenderId: '1095257635223',
    projectId: 'movievault-52674',
    storageBucket: 'movievault-52674.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpnZo6QBcjdPVmqEji_4DRgSiydhpFRa0',
    appId: '1:1095257635223:web:ccf545faa17a3f9169ecd2',
    messagingSenderId: '1095257635223',
    projectId: 'movievault-52674',
    authDomain: 'movievault-52674.firebaseapp.com',
    storageBucket: 'movievault-52674.firebasestorage.app',
    measurementId: 'G-GP8D729YNY',
  );
}
